version: '3.7'

services:
  standalone:
    deploy:
      replicas: 1
    image: standalone:1.3
    build: ./StandAlone
    ports: 
      - "8080:80"
  simplicity:
    deploy:
      replicas: 3
    image: simplicity:1.0
    build: ./Simplicity
    ports: 
      - "8081:80"
  dbapi:
    deploy:
      replicas: 3
    image: dbapi:1.0
    build: ./DbApi
    secrets:
      - DockThisDbConnection

secrets:
  DockThisDbConnection:
    external: true