version: '3.7'

services:
  standalone:
    build: ./StandAlone
    ports: 
      - "8080:80"
  simplicity:
    build: ./Simplicity
    ports: 
      - "8081:80"
  dbapi:
    build: ./DbApi
    secrets:
      - DockThisDbConnection

secrets:
  DockThisDbConnection:
    file: ./DockThisDbConnection.txt