#!/bin/bash

STANDALONETAG=${1:=latest}
SIMPLICITYTAG=${2:=latest}
DBAPITAG=${3:=latest}
NETWORKNAME=${4:=mydocnetwork}
	
echo "Building: standalone:$STANDALONETAG"
docker build -t standalone:$STANDALONETAG -f StandAloneDockerfile .

echo "Building: simplicity:$SIMPLICITYTAG"
docker build -t simplicity:$SIMPLICITYTAG -f SimplicityDockerfile .

echo "Building: dbapi:$DBAPITAG"
docker build -t dbapi:$DBAPITAG -f DbApiDockerfile .

echo "Pruning images"
docker image prune -f

echo "Build complete"
echo "To deploy, run   docker stack deploy --compose-file DockerStack.yml $NETWORKNAME"